# This file was used to check that the program understands how to create the DFA
# trees correctly

# https://en.wikipedia.org/wiki/Canonical_LR_parser#FIRST_and_FOLLOW_sets

# TOKEN n: {"[0-9]+"}
# S: E

# E: T
 # | '(' E ')'

# T: n
 # | '+' T
 # | T '+' n


# https://www.cs.bgu.ac.il/~romanm/wcc06/LR%20Parsing.pdf
# TOKEN i: {"[0-9]+"}

# START Z: test

# Z: E
# E: T
 # | E "+" T

# T: i
 # | "(" E ")"


# https://www.cs.clemson.edu/course/cpsc827/material/LRk/LR0.pdf
# TOKEN a: "a"
# TOKEN b: "b"
# TOKEN c: "c"

# S: A "#"
# A: a A b
 # | c


# https://www.javatpoint.com/canonical-collection-of-lr-0-items
TOKEN a: "a"
TOKEN b: "b"

START Z

Z: S
S: A A
A: a A
 | b
